{
OUT
3
10
10
2
3.0
3.0
3.0
3.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
-1
8
-8
0
-1.0
-1.0
-1.0
-1.0
-4.0
-4.0
4.0
4.0
-4.0
-4.0
4.0
4.0
2
9
9
1
2.0
2.0
2.0
2.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
}

;addition
println str(1+2)
println str(9+true)
println str(true+9)
println str(true+true)

println str(1.0+2.0)
println str(1.0+2.0f)
println str(1.0f+2.0)
println str(1.0f+2.0f)

println str(1+5.0)
println str(1+5.0f)
println str(5.0+1)
println str(5.0f+1)

println str(true+5.0)
println str(true+5.0f)
println str(5.0+true)
println str(5.0f+true)

;subtraction
println str(1-2)
println str(9-true)
println str(true-9)
println str(true-true)

println str(1.0-2.0)
println str(1.0-2.0f)
println str(1.0f-2.0)
println str(1.0f-2.0f)

println str(1-5.0)
println str(1-5.0f)
println str(5.0-1)
println str(5.0f-1)

println str(true-5.0)
println str(true-5.0f)
println str(5.0-true)
println str(5.0f-true)

;multiplication
println str(1*2)
println str(9*true)
println str(true*9)
println str(true*true)

println str(1.0*2.0)
println str(1.0*2.0f)
println str(1.0f*2.0)
println str(1.0f*2.0f)

println str(1*5.0)
println str(1*5.0f)
println str(5.0*1)
println str(5.0f*1)

println str(true*5.0)
println str(true*5.0f)
println str(5.0*true)
println str(5.0f*true)
